// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const AddKnowledgeOptions: CLICommandOption[] = [
  {
    name: "knowledge-source",
    type: "string",
    description: "Knowledge source.",
    required: true,
    default: "web-search",
    choices: ["web-search", "oneDrive-sharePoint", "embedded-knowledge"],
  },
  {
    name: "teams-manifest-file",
    questionName: "manifest-path",
    type: "string",
    shortName: "t",
    description:
      "Specify the path for Teams app manifest template. It can be either absolute path or relative path to the project root folder, with default at './appPackage/manifest.json'",
    default: "./appPackage/manifest.json",
  },
  {
    name: "embedded-knowledge-files",
    type: "string",
    description: "Select your embedded knowledge files.",
  },
];
export const AddKnowledgeArguments: CLICommandArgument[] = [];
