// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const AddKnowledgeOptions: CLICommandOption[] = [
  {
    name: "knowledge-source",
    type: "string",
    description: "Knowledge source.",
    required: true,
    default: "web-search",
    choices: ["web-search", "oneDrive-sharePoint", "graph-connector", "embedded-knowledge"],
  },
  {
    name: "search-type",
    type: "string",
    description: "Select Search Type",
  },
  {
    name: "web-content",
    type: "string",
    description: "Name of Web Content.",
  },
  {
    name: "teams-manifest-file",
    questionName: "manifest-path",
    type: "string",
    shortName: "t",
    description:
      "Specify the path for Teams app manifest template. It can be either absolute path or relative path to the project root folder, with default at './appPackage/manifest.json'",
    default: "./appPackage/manifest.json",
  },
  {
    name: "oneDriveSharePointURL",
    type: "string",
    description: "OneDrive or SharePoint Content",
    required: true,
  },
  {
    name: "oneDriveSharePointContent",
    type: "string",
    description: "OneDrive or SharePoint Content",
  },
  {
    name: "graph-connector-content",
    type: "string",
    description: "Graph Connector Content",
    choices: ["listConnections", "inputConnectionId"],
  },
  {
    name: "graph-connector-list",
    type: "array",
    description: "Select one or more Graph Connectors as knowledge source",
    default: [],
  },
  {
    name: "graph-connector-input",
    type: "string",
    description: "a connection ID for Graph Connector",
  },
  {
    name: "embedded-knowledge-files",
    type: "array",
    description: "Select your embedded knowledge files.",
  },
];
export const AddKnowledgeArguments: CLICommandArgument[] = [];
