// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const SetSensitivityLabelOptions: CLICommandOption[] = [
  {
    name: "declarative-agent-manifest-file",
    questionName: "declarative-agent-manifest-path",
    type: "string",
    shortName: "d",
    description:
      "Specify the path for the Declarative Agent manifest. It can be either absolute path or relative path to the project root folder, with default at './appPackage/declarativeAgent.json'",
    required: true,
    default: "./appPackage/declarativeAgent.json",
  },
  {
    name: "sensitivity-label",
    type: "string",
    shortName: "s",
    description: "Specify the sensitivity label to be set.",
    required: true,
    skipValidation: true,
  },
];
export const SetSensitivityLabelArguments: CLICommandArgument[] = [];
