// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const ShareOptions: CLICommandOption[] = [
  {
    name: "share-operation",
    type: "string",
    description: "Share the agent",
    required: true,
    choices: ["share", "unshare"],
  },
  {
    name: "scope",
    type: "string",
    description: "Share the agent with users",
    default: "users",
    choices: ["tenant", "users", "owners"],
  },
  {
    name: "email",
    type: "string",
    description: "Email address of specific users or groups separated by comma.",
  },
];
export const ShareArguments: CLICommandArgument[] = [];
