// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

export interface ValidationRule {
  id: string;
  code: string;
  severity: "error" | "warning";
  property: string;
  description: string;
  constraint: string;
}

export interface DiagnosticCodeInfo {
  name: string;
  severity: "error" | "warning";
  description: string;
}

/**
 * Validation rules for declarative agents (metadata for documentation)
 * Actual validation is performed by Rego policies
 */
export const DECLARATIVE_AGENT_RULES: ValidationRule[] = [
  // Root properties
  {
    id: "name-required",
    code: "M365-001",
    severity: "error",
    property: "name",
    description: "Name is required",
    constraint: "1-100 characters",
  },
  {
    id: "name-length",
    code: "M365-003",
    severity: "error",
    property: "name",
    description: "Name exceeds maximum length",
    constraint: "Maximum 100 characters",
  },
  {
    id: "description-required",
    code: "M365-001",
    severity: "error",
    property: "description",
    description: "Description is required",
    constraint: "1-1000 characters",
  },
  {
    id: "description-length",
    code: "M365-003",
    severity: "error",
    property: "description",
    description: "Description exceeds maximum length",
    constraint: "Maximum 1000 characters",
  },
  {
    id: "instructions-length",
    code: "M365-003",
    severity: "error",
    property: "instructions",
    description: "Instructions exceed maximum length",
    constraint: "Maximum 8000 characters",
  },
  // Instructions quality
  {
    id: "instructions-weak-language",
    code: "M365-010",
    severity: "warning",
    property: "instructions",
    description: "Weak/hedging language in instructions",
    constraint: "Use direct, imperative language",
  },
  {
    id: "instructions-ambiguity",
    code: "M365-011",
    severity: "warning",
    property: "instructions",
    description: "Ambiguous or vague terms in instructions",
    constraint: "Use specific quantities and criteria",
  },
  {
    id: "instructions-missing-persona",
    code: "M365-012",
    severity: "warning",
    property: "instructions",
    description: "Missing persona definition or insufficient detail",
    constraint: 'Include "You are..." role definition',
  },
  {
    id: "instructions-missing-capability",
    code: "M365-013",
    severity: "warning",
    property: "instructions",
    description: "Configured capabilities not mentioned in instructions",
    constraint: "Reference capabilities so agent knows when to use them",
  },
  {
    id: "instructions-redundancy",
    code: "M365-014",
    severity: "warning",
    property: "instructions",
    description: "Duplicate sentences in instructions",
    constraint: "Remove redundant instructions",
  },
  // LLM-powered instruction quality (opt-in)
  {
    id: "instructions-contradiction",
    code: "M365-015",
    severity: "warning",
    property: "instructions",
    description: "Contradictory instructions detected by LLM",
    constraint: "Resolve conflicting directives",
  },
  {
    id: "instructions-persona-inconsistency",
    code: "M365-016",
    severity: "warning",
    property: "instructions",
    description: "Persona traits conflict detected by LLM",
    constraint: "Ensure consistent personality",
  },
  {
    id: "instructions-cognitive-load",
    code: "M365-017",
    severity: "warning",
    property: "instructions",
    description: "Overly complex instructions detected by LLM",
    constraint: "Simplify nested conditions",
  },
  {
    id: "instructions-coverage-gap",
    code: "M365-018",
    severity: "warning",
    property: "instructions",
    description: "Coverage gap detected by LLM",
    constraint: "Address unhandled scenarios",
  },
  {
    id: "instructions-safety",
    code: "M365-019",
    severity: "warning",
    property: "instructions",
    description: "Safety or output format concern detected by LLM",
    constraint: "Add guardrails and format guidance",
  },
  // Conversation starters
  {
    id: "conversation-starters-max",
    code: "M365-003",
    severity: "error",
    property: "conversation_starters",
    description: "Too many conversation starters",
    constraint: "Maximum 12 items (v1.6)",
  },
  // Actions
  {
    id: "actions-max",
    code: "M365-003",
    severity: "error",
    property: "actions",
    description: "Too many actions",
    constraint: "Maximum 10 items",
  },
  // Worker agents
  {
    id: "worker-agents-max",
    code: "M365-003",
    severity: "error",
    property: "worker_agents",
    description: "Too many worker agents",
    constraint: "Maximum 10 items",
  },
  {
    id: "worker-agent-id-guid",
    code: "M365-002",
    severity: "error",
    property: "worker_agents[].id",
    description: "Worker agent ID must be valid GUID",
    constraint: "GUID format",
  },
  // Capabilities
  {
    id: "capability-duplicate",
    code: "M365-006",
    severity: "warning",
    property: "capabilities",
    description: "Duplicate capability type",
    constraint: "Each type once",
  },
  {
    id: "websearch-sites-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[WebSearch].sites",
    description: "Too many sites",
    constraint: "Maximum 4 sites",
  },
  {
    id: "websearch-url-path-segments",
    code: "M365-002",
    severity: "error",
    property: "capabilities[WebSearch].sites[].url",
    description: "URL has too many path segments",
    constraint: "Maximum 2 path segments",
  },
  {
    id: "email-group-mailboxes-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[Email].group_mailboxes",
    description: "Too many group mailboxes",
    constraint: "Maximum 25 items",
  },
  {
    id: "embedded-knowledge-files-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[EmbeddedKnowledge].files",
    description: "Too many files",
    constraint: "Maximum 10 files",
  },
  {
    id: "embedded-knowledge-extension",
    code: "M365-008",
    severity: "error",
    property: "capabilities[EmbeddedKnowledge].files[].file",
    description: "Invalid file extension",
    constraint: "doc, docx, ppt, pptx, xls, xlsx, txt, pdf",
  },
  // Name pattern
  {
    id: "name-pattern",
    code: "M365-002",
    severity: "error",
    property: "name",
    description: "Name contains invalid characters",
    constraint: "Only alphanumeric + underscore (^[a-zA-Z0-9_]*$)",
  },
  // Behavior overrides
  {
    id: "behavior-overrides-response-mode",
    code: "M365-002",
    severity: "error",
    property: "behavior_overrides.default_response_mode",
    description: "Invalid response mode value",
    constraint: "Auto, Quick response, Think deeper",
  },
  // User overrides
  {
    id: "user-override-path-required",
    code: "M365-001",
    severity: "error",
    property: "user_overrides[].path",
    description: "User override path is required",
    constraint: "Required property",
  },
  {
    id: "user-override-path-target",
    code: "M365-002",
    severity: "error",
    property: "user_overrides[].path",
    description: "Path must target capabilities",
    constraint: "Must start with $.capabilities",
  },
  {
    id: "user-override-allowed-actions",
    code: "M365-002",
    severity: "error",
    property: "user_overrides[].allowed_actions",
    description: "Invalid allowed action",
    constraint: "Only 'remove' is allowed",
  },
  // Worker agent structural rules
  {
    id: "worker-agent-id-file-mutual-exclusion",
    code: "M365-002",
    severity: "error",
    property: "worker_agents[]",
    description: "Worker agent id and file are mutually exclusive",
    constraint: "Provide one or the other",
  },
  // Conversation starter dependsOn
  {
    id: "conversation-starter-depends-on-name",
    code: "M365-002",
    severity: "error",
    property: "conversation_starters[].dependsOn[].name",
    description: "dependsOn name must be 'capabilities'",
    constraint: "Only 'capabilities' allowed",
  },
  {
    id: "conversation-starter-depends-on-id",
    code: "M365-002",
    severity: "error",
    property: "conversation_starters[].dependsOn[].id",
    description: "dependsOn ID must reference defined capability",
    constraint: "Must match a capability name",
  },
  // OneDrive/SharePoint
  {
    id: "onedrive-files-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[OneDriveAndSharePoint].items_by_url",
    description: "Too many OneDrive files",
    constraint: "Maximum 5 files",
  },
  {
    id: "sharepoint-files-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[OneDriveAndSharePoint].items_by_sharepoint_ids",
    description: "Too many SharePoint files",
    constraint: "Maximum 5 files",
  },
  {
    id: "onedrive-url-absolute",
    code: "M365-002",
    severity: "error",
    property: "capabilities[OneDriveAndSharePoint].items_by_url[].url",
    description: "URL must be absolute HTTP/HTTPS",
    constraint: "Absolute URL required",
  },
  {
    id: "sharepoint-file-name-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[OneDriveAndSharePoint].items_by_sharepoint_ids[].file_name",
    description: "file_name is required",
    constraint: "Required property",
  },
  {
    id: "sharepoint-part-id-type-together",
    code: "M365-002",
    severity: "error",
    property: "capabilities[OneDriveAndSharePoint].items_by_sharepoint_ids[]",
    description: "part_id and part_type must both be specified together",
    constraint: "Both or neither",
  },
  // Dataverse
  {
    id: "dataverse-knowledge-sources-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[Dataverse].knowledge_sources",
    description: "At least one knowledge source required",
    constraint: "Minimum 1 item",
  },
  {
    id: "dataverse-tables-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[Dataverse].knowledge_sources[].tables",
    description: "At least one table required",
    constraint: "Minimum 1 item",
  },
  {
    id: "dataverse-skill-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[Dataverse].knowledge_sources[].skill",
    description: "Skill is required",
    constraint: "Required property",
  },
  {
    id: "dataverse-hostname-valid",
    code: "M365-002",
    severity: "error",
    property: "capabilities[Dataverse].knowledge_sources[].host_name",
    description: "Invalid hostname format",
    constraint: "Valid DNS hostname",
  },
  {
    id: "dataverse-table-name-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[Dataverse].knowledge_sources[].tables[].table_name",
    description: "Table name too long",
    constraint: "Maximum 50 characters",
  },
  // Graph Connectors
  {
    id: "graph-connectors-unique-connection-id",
    code: "M365-006",
    severity: "warning",
    property: "capabilities[GraphConnectors].connections[].connection_id",
    description: "Duplicate connection_id",
    constraint: "Must be unique",
  },
  // Email
  {
    id: "email-folder-id-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[Email].folders[].folder_id",
    description: "folder_id is required",
    constraint: "Required property",
  },
  // Scenario Models
  {
    id: "scenario-models-tc-prefix-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[ScenarioModels].models",
    description: "Too many models with TC prefix",
    constraint: "Maximum 1 TC-prefixed model",
  },
  {
    id: "scenario-models-unique-ids",
    code: "M365-006",
    severity: "warning",
    property: "capabilities[ScenarioModels].models[].id",
    description: "Duplicate model ID",
    constraint: "Must be unique",
  },
  // Embedded Knowledge
  {
    id: "embedded-knowledge-resource-snapshot",
    code: "M365-003",
    severity: "error",
    property: "capabilities[EmbeddedKnowledge].files[].resource_snapshot_id",
    description: "resource_snapshot_id must not be empty if present",
    constraint: "Non-empty string",
  },
  // Meetings
  {
    id: "meetings-items-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[Meetings].items_by_id",
    description: "Too many meeting items",
    constraint: "Maximum 5 items",
  },
  {
    id: "meetings-item-id-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[Meetings].items_by_id[].id",
    description: "Meeting item ID is required",
    constraint: "Required property",
  },
  {
    id: "meetings-item-is-series-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[Meetings].items_by_id[].is_series",
    description: "Meeting item is_series is required",
    constraint: "Required boolean property",
  },
  // Editorial Answers
  {
    id: "editorial-answers-url-or-answers",
    code: "M365-001",
    severity: "error",
    property: "capabilities[EditorialAnswers]",
    description: "Must have url or answers (mutually exclusive)",
    constraint: "Exactly one of url or answers",
  },
  {
    id: "editorial-answers-url-absolute",
    code: "M365-002",
    severity: "error",
    property: "capabilities[EditorialAnswers].url",
    description: "URL must be absolute",
    constraint: "HTTP/HTTPS URL",
  },
  {
    id: "editorial-answers-max",
    code: "M365-003",
    severity: "error",
    property: "capabilities[EditorialAnswers].answers",
    description: "Too many answers",
    constraint: "Maximum 300 answers",
  },
  {
    id: "editorial-answers-question-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[EditorialAnswers].answers[].question",
    description: "Question is required",
    constraint: "Required property",
  },
  {
    id: "editorial-answers-text-required",
    code: "M365-001",
    severity: "error",
    property: "capabilities[EditorialAnswers].answers[].answer_text",
    description: "Answer text is required",
    constraint: "Required property",
  },
  {
    id: "editorial-answers-similarity-threshold",
    code: "M365-002",
    severity: "error",
    property: "capabilities[EditorialAnswers].similarity_threshold_*",
    description: "Similarity threshold out of range",
    constraint: "Must be between 0.0 and 10.0",
  },
];

/**
 * Validation rules for API plugins (metadata for documentation)
 */
export const API_PLUGIN_RULES: ValidationRule[] = [
  {
    id: "namespace-required",
    code: "M365-001",
    severity: "error",
    property: "namespace",
    description: "Namespace is required",
    constraint: "Pattern: ^[A-Za-z0-9_]+$",
  },
  {
    id: "namespace-pattern",
    code: "M365-002",
    severity: "error",
    property: "namespace",
    description: "Namespace contains invalid characters",
    constraint: "Only alphanumeric + hyphens (^[A-Za-z0-9-]+$)",
  },
  {
    id: "name-for-human-length",
    code: "M365-005",
    severity: "warning",
    property: "name_for_human",
    description: "Name may be truncated",
    constraint: "Max 20 characters",
  },
  {
    id: "description-for-model-length",
    code: "M365-005",
    severity: "warning",
    property: "description_for_model",
    description: "Description may be truncated",
    constraint: "Max 2048 characters recommended",
  },
  {
    id: "function-name-required",
    code: "M365-001",
    severity: "error",
    property: "functions[].name",
    description: "Function name is required",
    constraint: "Required property",
  },
  {
    id: "function-name-pattern",
    code: "M365-002",
    severity: "error",
    property: "functions[].name",
    description: "Function name contains invalid characters",
    constraint: "Only alphanumeric, underscores, hyphens",
  },
  {
    id: "function-name-unique",
    code: "M365-006",
    severity: "warning",
    property: "functions[].name",
    description: "Duplicate function name",
    constraint: "Must be unique",
  },
  {
    id: "function-description-required",
    code: "M365-001",
    severity: "error",
    property: "functions[].description",
    description: "Function description is required",
    constraint: "Required property",
  },
  {
    id: "function-description-max-length",
    code: "M365-003",
    severity: "error",
    property: "functions[].description",
    description: "Function description too long",
    constraint: "Maximum 1024 characters",
  },
  {
    id: "namespace-function-name-combined-max",
    code: "M365-003",
    severity: "error",
    property: "namespace + functions[].name",
    description: "Namespace + function name combined too long",
    constraint: "Maximum 64 characters combined",
  },
  {
    id: "function-parameters-type",
    code: "M365-002",
    severity: "error",
    property: "functions[].parameters.type",
    description: "Parameters type must be 'object'",
    constraint: "Only 'object' allowed",
  },
  {
    id: "function-returns-type",
    code: "M365-002",
    severity: "error",
    property: "functions[].returns.type",
    description: "Returns type must be 'string'",
    constraint: "Only 'string' allowed",
  },
  {
    id: "function-parameter-property-type",
    code: "M365-002",
    severity: "error",
    property: "functions[].parameters.properties[].type",
    description: "Invalid parameter property type",
    constraint: "string, array, boolean, integer, number",
  },
  {
    id: "function-parameter-items-only-array",
    code: "M365-002",
    severity: "error",
    property: "functions[].parameters.properties[].items",
    description: "items only valid for array type",
    constraint: "Requires type=array",
  },
  {
    id: "security-info-data-handling",
    code: "M365-002",
    severity: "error",
    property: "security_info.data_handling[]",
    description: "Invalid data_handling value",
    constraint: "GetPublicData, GetPrivateData, DataTransform, ResourceStateUpdate, DataExport",
  },
  {
    id: "logo-url-absolute",
    code: "M365-002",
    severity: "error",
    property: "logo_url",
    description: "Logo URL must be absolute",
    constraint: "HTTP/HTTPS URL",
  },
  {
    id: "contact-email-valid",
    code: "M365-002",
    severity: "error",
    property: "contact_email",
    description: "Invalid email address",
    constraint: "Valid email format",
  },
  {
    id: "legal-info-url-absolute",
    code: "M365-002",
    severity: "error",
    property: "legal_info_url",
    description: "Legal info URL must be absolute",
    constraint: "HTTP/HTTPS URL",
  },
  {
    id: "privacy-policy-url-absolute",
    code: "M365-002",
    severity: "error",
    property: "privacy_policy_url",
    description: "Privacy policy URL must be absolute",
    constraint: "HTTP/HTTPS URL",
  },
  {
    id: "runtime-auth-required",
    code: "M365-001",
    severity: "error",
    property: "runtimes[].auth",
    description: "Runtime auth configuration is required",
    constraint: "Required property",
  },
  {
    id: "runtime-auth-reference-id",
    code: "M365-001",
    severity: "error",
    property: "runtimes[].auth.reference_id",
    description: "reference_id required for vault auth types",
    constraint: "Required for OAuthPluginVault and ApiKeyPluginVault",
  },
  {
    id: "runtime-spec-url-or-description",
    code: "M365-001",
    severity: "error",
    property: "runtimes[].spec",
    description: "Spec requires url or api_description",
    constraint: "At least one required",
  },
  {
    id: "runtime-spec-url-absolute",
    code: "M365-002",
    severity: "error",
    property: "runtimes[].spec.url",
    description: "Spec URL must be absolute",
    constraint: "HTTP/HTTPS URL",
  },
  {
    id: "mcp-runtime-run-for-functions",
    code: "M365-003",
    severity: "error",
    property: "runtimes[].run_for_functions",
    description: "MCP runtime needs at least 1 function",
    constraint: "Minimum 1 item for McpServer type",
  },
];

/**
 * Diagnostic codes used by the validator
 */
export const DIAGNOSTIC_CODES: Record<string, DiagnosticCodeInfo> = {
  "M365-001": {
    name: "Missing required property",
    severity: "error",
    description: "A required property is missing",
  },
  "M365-002": {
    name: "Invalid format",
    severity: "error",
    description: "Invalid format (URL, email, GUID, etc.)",
  },
  "M365-003": {
    name: "Constraint violation",
    severity: "error",
    description: "Violates a constraint (length, count)",
  },
  "M365-004": {
    name: "Schema validation failure",
    severity: "error",
    description: "Fails JSON schema validation",
  },
  "M365-005": {
    name: "Length warning",
    severity: "warning",
    description: "Exceeds recommended length",
  },
  "M365-006": {
    name: "Duplicate values",
    severity: "warning",
    description: "Array contains duplicates",
  },
  "M365-007": {
    name: "File not found",
    severity: "error",
    description: "Referenced file does not exist",
  },
  "M365-008": {
    name: "Invalid file extension",
    severity: "error",
    description: "Unsupported extension",
  },
  "M365-009": {
    name: "Performance concern",
    severity: "warning",
    description: "May cause performance issues",
  },
  "M365-010": {
    name: "Weak language",
    severity: "warning",
    description: "Instructions use hedging/weak language",
  },
  "M365-011": {
    name: "Ambiguity",
    severity: "warning",
    description: "Instructions contain ambiguous terms",
  },
  "M365-012": {
    name: "Missing persona",
    severity: "warning",
    description: "Missing persona definition or insufficient detail",
  },
  "M365-013": {
    name: "Missing capability mention",
    severity: "warning",
    description: "Capabilities not referenced in instructions",
  },
  "M365-014": {
    name: "Redundancy",
    severity: "warning",
    description: "Duplicate sentences in instructions",
  },
  "M365-015": {
    name: "Contradiction",
    severity: "warning",
    description: "Contradictory instructions detected (LLM)",
  },
  "M365-016": {
    name: "Persona inconsistency",
    severity: "warning",
    description: "Persona traits conflict (LLM)",
  },
  "M365-017": {
    name: "Cognitive load",
    severity: "warning",
    description: "Overly complex instructions (LLM)",
  },
  "M365-018": {
    name: "Coverage gap",
    severity: "warning",
    description: "Unhandled scenarios (LLM)",
  },
  "M365-019": {
    name: "Output shape / safety",
    severity: "warning",
    description: "Output format or safety concern (LLM)",
  },
};
