// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// This file list feature flag settings that should be handled during release.
// Please do not edit this file except introducing new feature flag settings.
// During cd, we will toggle the value of the feature flag settings in this file from "false" to "true" on alpha and beta version.
// Please list each setting line by line. The default value should be the expected value in stable release, which is false usually.
const shouldHideTeamsAgentPreviewTag = false;

export const releaseControlledFeatureSettings = {
  shouldEnableTeamsCopilotChatUI: false,
  shouldHideTeamsAgentPreviewTag,
};
