// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface AddKnowledgeInputs extends Inputs {
  /** @description Add Knowledge */
  "knowledge-source"?:
    | "web-search"
    | "oneDrive-sharePoint"
    | "graph-connector"
    | "embedded-knowledge";
  /** @description Select Search Type */
  "search-type"?: string;
  /** @description Web Content */
  "web-content"?: string;
  /** @description Select Teams manifest.json File */
  "manifest-path"?: string;
  /** @description OneDrive or SharePoint Content */
  oneDriveSharePointURL?: string;
  /** @description OneDrive or SharePoint Content */
  oneDriveSharePointContent?: string;
  /** @description Graph Connector Content */
  "graph-connector-content"?: "listConnections" | "inputConnectionId";
  /** @description Select one or more Graph Connectors as knowledge source */
  "graph-connector-list"?: string[];
  /** @description Connection ID */
  "graph-connector-input"?: string;
  /** @description Add embedded knowledge files */
  "embedded-knowledge-files"?: string[];
}
