// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface ShareInputs extends Inputs {
  /** @description Share the agent */
  "share-operation"?: "share" | "unshare";
  /** @description Share the agent with users */
  scope?: "tenant" | "users" | "owners";
  /** @description Email addresses of users for agent sharing */
  email?: string;
}
